In [1]:
import torch

In [2]:
t1 = torch.tensor(11)
t2 = torch.tensor([1,2])
t3 = torch.tensor([[1,1,3],[2,2,6]])

In [3]:
print(t1.dtype)
print(t1.shape)
print(t1.device)

torch.int64
torch.Size([])
cpu


In [4]:
t4 = torch.tensor([[15.0,5.0],[11,0]])

In [5]:
# Scalar multiply or scalar operation

t4*10 == t4.multiply(10)

t4-11 == t4.subtract(11)

tensor([[True, True],
        [True, True]])

In [6]:
# dot product or matrix multiplication
t5 = torch.tensor([[1,2],[1,2]])
t5.T # -> tensor transpose

tensor([[1, 1],
        [2, 2]])

In [7]:
t5 * t5 # element-wise multiplication

tensor([[1, 4],
        [1, 4]])

In [8]:
%%time
print(torch.matmul(t5,t5) == t5 @ t5)
print(torch.matmul(t5,t5) == torch.mm(t5,t5))
# torch.mm is alias for torch.matmul

tensor([[True, True],
        [True, True]])
tensor([[True, True],
        [True, True]])
CPU times: total: 15.6 ms
Wall time: 19.6 ms


In [9]:
%%time
A=torch.tensor([[1,2,3],[4,5,6]])
B= torch.tensor([[7,8],[9,10],[11,12]])
print(torch.matmul(A,B))

tensor([[ 58,  64],
        [139, 154]])
CPU times: total: 0 ns
Wall time: 0 ns


In [10]:
x_org = torch.rand(255,255,3)

In [11]:
x_org.view([3,255,255])

tensor([[[0.0201, 0.9789, 0.5546,  ..., 0.2442, 0.7997, 0.9864],
         [0.0873, 0.3959, 0.4814,  ..., 0.6875, 0.5391, 0.7684],
         [0.3146, 0.7068, 0.3816,  ..., 0.6585, 0.3217, 0.9833],
         ...,
         [0.1795, 0.3622, 0.3194,  ..., 0.1264, 0.5826, 0.7394],
         [0.2357, 0.9034, 0.3613,  ..., 0.8126, 0.4111, 0.1520],
         [0.7837, 0.6831, 0.1988,  ..., 0.4942, 0.2957, 0.3966]],

        [[0.6208, 0.9655, 0.6255,  ..., 0.5328, 0.0671, 0.4124],
         [0.1592, 0.8095, 0.4548,  ..., 0.5064, 0.2385, 0.0603],
         [0.1679, 0.4517, 0.0277,  ..., 0.8453, 0.7051, 0.9088],
         ...,
         [0.2734, 0.1987, 0.9008,  ..., 0.7845, 0.7213, 0.0796],
         [0.9031, 0.5541, 0.2807,  ..., 0.0951, 0.1519, 0.3750],
         [0.0993, 0.3139, 0.3029,  ..., 0.4209, 0.7958, 0.3772]],

        [[0.4363, 0.8840, 0.7924,  ..., 0.7975, 0.8732, 0.3916],
         [0.0534, 0.1957, 0.5336,  ..., 0.8456, 0.8421, 0.3204],
         [0.3841, 0.3525, 0.6992,  ..., 0.7572, 0.2871, 0.

In [12]:
x_per = x_org.permute(2,1,0)
x_per

tensor([[[0.0201, 0.7458, 0.3112,  ..., 0.9487, 0.0215, 0.5692],
         [0.2413, 0.3953, 0.2309,  ..., 0.0012, 0.9019, 0.5570],
         [0.0288, 0.7340, 0.0724,  ..., 0.5662, 0.4285, 0.0870],
         ...,
         [0.6663, 0.6669, 0.2787,  ..., 0.1254, 0.0910, 0.9389],
         [0.3758, 0.3622, 0.5064,  ..., 0.5109, 0.7787, 0.6219],
         [0.6585, 0.6123, 0.2433,  ..., 0.0375, 0.2716, 0.0554]],

        [[0.9789, 0.4589, 0.1337,  ..., 0.4985, 0.0285, 0.0935],
         [0.5677, 0.8582, 0.9843,  ..., 0.7300, 0.6749, 0.9708],
         [0.9390, 0.8765, 0.2989,  ..., 0.6735, 0.2963, 0.3712],
         ...,
         [0.4197, 0.8732, 0.7719,  ..., 0.1888, 0.3004, 0.7930],
         [0.2274, 0.9689, 0.8686,  ..., 0.0876, 0.8110, 0.3331],
         [0.3217, 0.1597, 0.8889,  ..., 0.9128, 0.3795, 0.6069]],

        [[0.5546, 0.9896, 0.2038,  ..., 0.3066, 0.4390, 0.9680],
         [0.5965, 0.9856, 0.4593,  ..., 0.5054, 0.0980, 0.1094],
         [0.1590, 0.7224, 0.7361,  ..., 0.4270, 0.9766, 0.

In [13]:
x_org[0,0,0]= 172
x_per[0,0,0]

tensor(172.)

In [14]:
x= torch.arange(1,10).reshape([1,3,3])
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [15]:
x_squ=x.squeeze(0)
x_squ, x.shape, x_squ.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([1, 3, 3]),
 torch.Size([3, 3]))

In [16]:
x[0], x[0][1], x[0][1][2]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([4, 5, 6]),
 tensor(6))

In [17]:
x[:, 1, :], x[:, :, 1]

(tensor([[4, 5, 6]]), tensor([[2, 5, 8]]))

## Pytorch & Numpy

### numpy -> torch -> torch.from_numpy(ndarray)
### torch -> numpy -> torch.numpy()

In [18]:
import torch 
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.arange(1.,8.)
# array == tensor,
print(array.dtype == tensor.dtype)
tensor = torch.from_numpy(array)
print(array.dtype, tensor.dtype)
# default value of tensor in pytorch is torch.float32
tensor = torch.from_numpy(array).type(torch.float32)

False
float64 torch.float64


In [19]:
# Tensor to numpy
tensor = torch.ones((3,3))
np_tensor = tensor.numpy()
tensor, np_tensor

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32))

In [20]:
randA = torch.rand((2))
randB = torch.rand((2))
randA, randB, randA == randB

(tensor([0.5675, 0.0955]), tensor([0.8244, 0.5259]), tensor([False, False]))

In [21]:
RANDOM_SEED=42

torch.manual_seed(RANDOM_SEED)
randC = torch.rand(4)
randD = torch.rand(4)
torch.manual_seed(RANDOM_SEED)
randC, randD, randC == randD

(tensor([0.8823, 0.9150, 0.3829, 0.9593]),
 tensor([0.3904, 0.6009, 0.2566, 0.7936]),
 tensor([False, False, False, False]))

## Runnong pytorch obj and tensors on GPU

In [22]:
!nvidia-smi

Tue Mar 11 09:54:39 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 566.36                 Driver Version: 566.36         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   43C    P8              6W /   50W |       0MiB /   6144MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### Check for GPU access with Pytorch

In [23]:
import torch
torch.cuda.is_available()

True

In [24]:
%%time
torchA = torch.rand((8,8,8,8,8,8,8,8), device="cpu")
torchA.device

CPU times: total: 156 ms
Wall time: 182 ms


device(type='cpu')

In [25]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [26]:
%%time
torchA = torch.rand((8,8,8,8,8,8,8,8), device=device)
torchA.device

CPU times: total: 453 ms
Wall time: 541 ms


device(type='cuda', index=0)

## Setting up Device Agnostic program
### Note: Numpy only works on cpu (use tensor.cpu() )

In [27]:
%%time
# create tensor (default on cpu)
tensorA = torch.tensor([1,2,3], device="cpu")

# move tensor to gpu (if available)
device = "cuda" if torch.cuda.is_available() else "cpu"
tensorB = torch.tensor([1,2,3], device=device)
tensorA.device, tensorB.device

CPU times: total: 0 ns
Wall time: 5.88 ms


(device(type='cpu'), device(type='cuda', index=0))

In [28]:
tensorA.numpy(), tensorB.numpy()
# TypeError: ca't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.b

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [30]:
tensorA.numpy(), tensorB.cpu().numpy()

(array([1, 2, 3]), array([1, 2, 3]))